# BookRental Recommendation System

In [258]:
import os
os.chdir('F:\Avantika University\Semester 6\AI\Assignment 3')
os.getcwd()

'F:\\Avantika University\\Semester 6\\AI\\Assignment 3'

In [259]:
import pandas as pd
import numpy as np
import seaborn as sn
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [260]:
data_user = pd.read_csv('BX-Users.csv',nrows =10000,encoding='latin-1')

In [261]:
data_books = pd.read_csv('BX-Books.csv',nrows =10000,encoding='latin-1')

In [262]:
data_books_ratings = pd.read_csv('BX-Book-Ratings.csv',nrows =10000,encoding='latin-1')

In [263]:
data_user

user_id                              Location   Age
0           1                    nyc, new york, usa   NaN
1           2             stockton, california, usa  18.0
2           3       moscow, yukon territory, russia   NaN
3           4             porto, v.n.gaia, portugal  17.0
4           5    farnborough, hants, united kingdom   NaN
...       ...                                   ...   ...
9995     9996  reynella, south australia, australia  29.0
9996     9997             willisburg, kentucky, usa  56.0
9997     9998                 warren, michigan, usa   NaN
9998     9999                beaverton, oregon, usa   NaN
9999    10000            jacksonville, florida, usa  38.0

[10000 rows x 3 columns]

In [264]:
data_user.describe()

user_id          Age
count  10000.00000  6273.000000
mean    5000.50000    32.415431
std     2886.89568    14.038664
min        1.00000     0.000000
25%     2500.75000    23.000000
50%     5000.50000    30.000000
75%     7500.25000    40.000000
max    10000.00000   239.000000

In [265]:
data_user.isnull().sum()

user_id        0
Location       0
Age         3727
dtype: int64

In [266]:
data_books

isbn                                         book_title  \
0      195153448                                Classical Mythology   
1        2005018                                       Clara Callan   
2       60973129                               Decision in Normandy   
3      374157065  Flu: The Story of the Great Influenza Pandemic...   
4      393045218                             The Mummies of Urumchi   
...          ...                                                ...   
9995   140283404  Beloved (Penguin Great Books of the 20th Century)   
9996   380730774  Read This and Tell Me What It Says : Stories (...   
9997   862418879                                     The Star Rover   
9998  340414645X                                   Die Keltennadel.   
9999  3442730988                                Tod in der Datscha.   

               book_author year_of_publication                   publisher  
0       Mark P. O. Morford                2002     Oxford University Press  
1     Richard Bruce Wright                2001       HarperFlamingo Canada  
2             Carlo D'Este                1991             HarperPerennial  
3         Gina Bari Kolata                1999        Farrar Straus Giroux  
4          E. J. W. Barber                1999  W. W. Norton &amp; Company  
...                    ...                 ...                         ...  
9995         Toni Morrison                2000               Penguin Books  
9996      A. Manette Ansay                1998              William Morrow  
9997           Jack London                2000             Canongate Books  
9998         Patrick Dunne                2001                    L�¼bbe  
9999       Anna Malyschewa                2003                         btb  

[10000 rows x 5 columns]

In [267]:
data_books.describe()

isbn                                       book_title  \
count       10000                                            10000   
unique      10000                                             9553   
top     385495641  The Golden Compass (His Dark Materials, Book 1)   
freq            1                                                5   

         book_author year_of_publication         publisher  
count          10000               10000             10000  
unique          5754                  63              1702  
top     Stephen King                2002  Ballantine Books  
freq              68                 919               300

In [268]:
data_books.isnull().sum()

isbn                   0
book_title             0
book_author            0
year_of_publication    0
publisher              0
dtype: int64

In [269]:
data_books.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   isbn                 10000 non-null  object
 1   book_title           10000 non-null  object
 2   book_author          10000 non-null  object
 3   year_of_publication  10000 non-null  object
 4   publisher            10000 non-null  object
dtypes: object(5)
memory usage: 390.8+ KB


In [270]:
data_books.head()

isbn                                         book_title  \
0  195153448                                Classical Mythology   
1    2005018                                       Clara Callan   
2   60973129                               Decision in Normandy   
3  374157065  Flu: The Story of the Great Influenza Pandemic...   
4  393045218                             The Mummies of Urumchi   

            book_author year_of_publication                   publisher  
0    Mark P. O. Morford                2002     Oxford University Press  
1  Richard Bruce Wright                2001       HarperFlamingo Canada  
2          Carlo D'Este                1991             HarperPerennial  
3      Gina Bari Kolata                1999        Farrar Straus Giroux  
4       E. J. W. Barber                1999  W. W. Norton &amp; Company

In [271]:
data_books_ratings

user_id        isbn  rating
0      276725  034545104X       0
1      276726   155061224       5
2      276727   446520802       0
3      276729  052165615X       3
4      276729   521795028       6
...       ...         ...     ...
9995      243   425164403       0
9996      243   440224764       0
9997      243   440225701       0
9998      243   440226430       0
9999      243   440234743       0

[10000 rows x 3 columns]

In [272]:
data_book = pd.merge(data_books_ratings,data_books,on='isbn')

In [273]:
data_book

user_id        isbn  rating  \
0      276725  034545104X       0   
1      276744  038550120X       7   
2      278418  038550120X       0   
3      276746   425115801       0   
4      277427   425115801       0   
...       ...         ...     ...   
1824      243   380807866       0   
1825      243   385316895       6   
1826      243   385509456       0   
1827      243   385720106       7   
1828      243   425164403       0   

                                             book_title  \
0                                  Flesh Tones: A Novel   
1                                       A Painted House   
2                                       A Painted House   
3                                             Lightning   
4                                             Lightning   
...                                                 ...   
1824                                  The Elusive Flame   
1825                                  Legacy of Silence   
1826  The Curious Incident of the Dog in the Night-T...   
1827                                 A Map of the World   
1828                           Only Love (Magical Love)   

                book_author year_of_publication                 publisher  
0                M. J. Rose                2002          Ballantine Books  
1              JOHN GRISHAM                2001                 Doubleday  
2              JOHN GRISHAM                2001                 Doubleday  
3            Dean R. Koontz                1996  Berkley Publishing Group  
4            Dean R. Koontz                1996  Berkley Publishing Group  
...                     ...                 ...                       ...  
1824  Kathleen E. Woodiwiss                1999                      Avon  
1825            Belva Plain                1998     Bantam Dell Pub Group  
1826            MARK HADDON                2003                 Doubleday  
1827          Jane Hamilton                1999    Anchor Books/Doubleday  
1828            Erich Segal                1998  Berkley Publishing Group  

[1829 rows x 7 columns]

In [325]:
data_book.nunique()

rating             11
user_id_index     465
book_id_index    1366
dtype: int64

In [275]:
data_book.isnull().sum()

user_id                0
isbn                   0
rating                 0
book_title             0
book_author            0
year_of_publication    0
publisher              0
dtype: int64

In [276]:
data_book.info

<bound method DataFrame.info of       user_id        isbn  rating  \
0      276725  034545104X       0   
1      276744  038550120X       7   
2      278418  038550120X       0   
3      276746   425115801       0   
4      277427   425115801       0   
...       ...         ...     ...   
1824      243   380807866       0   
1825      243   385316895       6   
1826      243   385509456       0   
1827      243   385720106       7   
1828      243   425164403       0   

                                             book_title  \
0                                  Flesh Tones: A Novel   
1                                       A Painted House   
2                                       A Painted House   
3                                             Lightning   
4                                             Lightning   
...                                                 ...   
1824                                  The Elusive Flame   
1825                                  Legacy of Sil

In [277]:
data_book.describe()

user_id       rating
count    1829.000000  1829.000000
mean   240554.414434     3.088026
std     94802.011078     3.906933
min         2.000000     0.000000
25%    277195.000000     0.000000
50%    277884.000000     0.000000
75%    278418.000000     7.000000
max    278854.000000    10.000000

In [278]:
data_book.shape

(1829, 7)

In [279]:
data_book.corr()

user_id   rating
user_id  1.00000 -0.07885
rating  -0.07885  1.00000

In [280]:
from sklearn.model_selection import train_test_split

In [281]:
data_book.columns

Index(['user_id', 'isbn', 'rating', 'book_title', 'book_author',
       'year_of_publication', 'publisher'],
      dtype='object')

In [282]:
n_users=data_book.user_id.unique().shape[0]

In [283]:
n_books=data_book.isbn.unique().shape[0]

In [284]:
train_data,test_data=train_test_split(data_book,test_size=0.25)

In [285]:
train_data_matrix=np.zeros((n_users,n_books))

In [286]:
train_data_matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [287]:
train_data

user_id       isbn  rating  \
448    277378  446322180       0   
1604   278633  515131083      10   
179    276964  886773741       7   
1108   278144  399139087       0   
872    277759  553211404       7   
...       ...        ...     ...   
1084   278137  440940001       8   
1466   278418  590224735       0   
184    277378  689817851       0   
691    277478  425161242       0   
751    278418   64400557       0   

                                           book_title            book_author  \
448                              Name of the Rose-Nla            Umberto Eco   
1604                    Plantation: A Lowcountry Tale  Dorothea Benton Frank   
179                                 Tailchaser's Song           Tad Williams   
1108                                    Second Nature          Alice Hoffman   
872                       Jane Eyre (Bantam Classics)       Charlotte Bronte   
...                                               ...                    ...   
1084  Island of the Blue Dolphins (Laurel Leaf Books)           Scott O'Dell   
1466  Kristy's Great Idea (The Baby-Sitter's Club #1)          Ann M. Martin   
184                                      Go Ask Alice              Anonymous   
691                                      Chromosome 6             Robin Cook   
751                  Charlotte's Web (Trophy Newbery)            E. B. White   

     year_of_publication                 publisher  
448                 1984              Warner Books  
1604                2001                Jove Books  
179                 1994                 Daw Books  
1108                1994          Putnam Pub Group  
872                 1983                    Bantam  
...                  ...                       ...  
1084                1978                Laure Leaf  
1466                1995                Scholastic  
184                 1998               Simon Pulse  
691                 2000  Berkley Publishing Group  
751                 1974              HarperTrophy  

[1371 rows x 7 columns]

In [288]:
print(n_users,n_books)

465 1366


In [289]:
book_list=data_book.isbn.unique()

In [290]:
user_list=data_book.user_id.unique()

In [291]:
book_list


array(['034545104X', '038550120X', '425115801', ..., '385509456',
       '385720106', '425164403'], dtype=object)

In [292]:
user_list

array([276725, 276744, 278418, 276746, 277427, 278026, 276747, 278843,
       276754, 276964, 276755,     99, 276762, 276788, 278356, 276796,
       277195,    232, 276798, 277375, 276800, 278100, 276804, 276811,
       276904, 278314, 276822, 276828, 277681, 276832, 277143, 276837,
       276838, 276840, 278633, 276847, 276848, 276936, 276856, 276862,
       276866, 278778, 276869, 278251, 276872, 276875, 277712, 276878,
       276884, 276887, 276888, 276889, 277523, 277710, 276896, 278194,
       276911, 276925, 277623, 277413, 277439, 277752, 277965,    243,
       277589, 277648, 277689, 278137, 278221, 278390,     67, 276939,
       276954, 277042, 277157, 277378, 277478, 277530, 277932, 278176,
       278373, 278514,     14,    193,    242,     68, 276928, 276929,
       277253, 278162, 276953, 277743,     26, 276957, 278582, 278774,
       276984, 276986, 276988, 276989, 276994, 278563, 276998, 277009,
       277018, 277032, 277036, 277928, 277639, 278483, 278773, 278535,
      

In [293]:
def get_bookisbn_index(isbn):
    itemindex=np.where(book_list==isbn)
    return itemindex[0][0]

In [294]:
def get_userid_index(user_id):
    itemindex=np.where(user_list==user_id)
    return itemindex[0][0]

In [295]:
data_book

user_id        isbn  rating  \
0      276725  034545104X       0   
1      276744  038550120X       7   
2      278418  038550120X       0   
3      276746   425115801       0   
4      277427   425115801       0   
...       ...         ...     ...   
1824      243   380807866       0   
1825      243   385316895       6   
1826      243   385509456       0   
1827      243   385720106       7   
1828      243   425164403       0   

                                             book_title  \
0                                  Flesh Tones: A Novel   
1                                       A Painted House   
2                                       A Painted House   
3                                             Lightning   
4                                             Lightning   
...                                                 ...   
1824                                  The Elusive Flame   
1825                                  Legacy of Silence   
1826  The Curious Incident of the Dog in the Night-T...   
1827                                 A Map of the World   
1828                           Only Love (Magical Love)   

                book_author year_of_publication                 publisher  
0                M. J. Rose                2002          Ballantine Books  
1              JOHN GRISHAM                2001                 Doubleday  
2              JOHN GRISHAM                2001                 Doubleday  
3            Dean R. Koontz                1996  Berkley Publishing Group  
4            Dean R. Koontz                1996  Berkley Publishing Group  
...                     ...                 ...                       ...  
1824  Kathleen E. Woodiwiss                1999                      Avon  
1825            Belva Plain                1998     Bantam Dell Pub Group  
1826            MARK HADDON                2003                 Doubleday  
1827          Jane Hamilton                1999    Anchor Books/Doubleday  
1828            Erich Segal                1998  Berkley Publishing Group  

[1829 rows x 7 columns]

In [296]:
data_book['user_id']

0       276725
1       276744
2       278418
3       276746
4       277427
         ...  
1824       243
1825       243
1826       243
1827       243
1828       243
Name: user_id, Length: 1829, dtype: int64

In [297]:
data_book[['user_id','isbn']]

user_id        isbn
0      276725  034545104X
1      276744  038550120X
2      278418  038550120X
3      276746   425115801
4      277427   425115801
...       ...         ...
1824      243   380807866
1825      243   385316895
1826      243   385509456
1827      243   385720106
1828      243   425164403

[1829 rows x 2 columns]

In [298]:
data_book['user_id_index']=data_book['user_id'].apply(get_userid_index)

In [299]:
data_book.columns

Index(['user_id', 'isbn', 'rating', 'book_title', 'book_author',
       'year_of_publication', 'publisher', 'user_id_index'],
      dtype='object')

In [300]:
data_book['book_id_index']=data_book['isbn'].apply(get_bookisbn_index)

In [301]:
data_book.columns

Index(['user_id', 'isbn', 'rating', 'book_title', 'book_author',
       'year_of_publication', 'publisher', 'user_id_index', 'book_id_index'],
      dtype='object')

In [302]:
data_book

user_id        isbn  rating  \
0      276725  034545104X       0   
1      276744  038550120X       7   
2      278418  038550120X       0   
3      276746   425115801       0   
4      277427   425115801       0   
...       ...         ...     ...   
1824      243   380807866       0   
1825      243   385316895       6   
1826      243   385509456       0   
1827      243   385720106       7   
1828      243   425164403       0   

                                             book_title  \
0                                  Flesh Tones: A Novel   
1                                       A Painted House   
2                                       A Painted House   
3                                             Lightning   
4                                             Lightning   
...                                                 ...   
1824                                  The Elusive Flame   
1825                                  Legacy of Silence   
1826  The Curious Incident of the Dog in the Night-T...   
1827                                 A Map of the World   
1828                           Only Love (Magical Love)   

                book_author year_of_publication                 publisher  \
0                M. J. Rose                2002          Ballantine Books   
1              JOHN GRISHAM                2001                 Doubleday   
2              JOHN GRISHAM                2001                 Doubleday   
3            Dean R. Koontz                1996  Berkley Publishing Group   
4            Dean R. Koontz                1996  Berkley Publishing Group   
...                     ...                 ...                       ...   
1824  Kathleen E. Woodiwiss                1999                      Avon   
1825            Belva Plain                1998     Bantam Dell Pub Group   
1826            MARK HADDON                2003                 Doubleday   
1827          Jane Hamilton                1999    Anchor Books/Doubleday   
1828            Erich Segal                1998  Berkley Publishing Group   

      user_id_index  book_id_index  
0                 0              0  
1                 1              1  
2                 2              1  
3                 3              2  
4                 4              2  
...             ...            ...  
1824             63           1361  
1825             63           1362  
1826             63           1363  
1827             63           1364  
1828             63           1365  

[1829 rows x 9 columns]

In [303]:
data_book[['user_id_index','book_id_index']]

user_id_index  book_id_index
0                 0              0
1                 1              1
2                 2              1
3                 3              2
4                 4              2
...             ...            ...
1824             63           1361
1825             63           1362
1826             63           1363
1827             63           1364
1828             63           1365

[1829 rows x 2 columns]

In [304]:
train_data_matrix=np.zeros((n_users,n_books))

In [305]:
train_data_matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [306]:
data_book.drop(['book_title','book_author'], axis = 1, inplace = True)

In [307]:
data_book.drop(['year_of_publication','publisher'], axis = 1, inplace = True)

In [308]:
data_book.drop(['user_id','isbn'], axis = 1, inplace = True)

In [309]:
data_book

rating  user_id_index  book_id_index
0          0              0              0
1          7              1              1
2          0              2              1
3          0              3              2
4          0              4              2
...      ...            ...            ...
1824       0             63           1361
1825       6             63           1362
1826       0             63           1363
1827       7             63           1364
1828       0             63           1365

[1829 rows x 3 columns]

In [310]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1371 entries, 448 to 751
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   user_id              1371 non-null   int64 
 1   isbn                 1371 non-null   object
 2   rating               1371 non-null   int64 
 3   book_title           1371 non-null   object
 4   book_author          1371 non-null   object
 5   year_of_publication  1371 non-null   object
 6   publisher            1371 non-null   object
dtypes: int64(2), object(5)
memory usage: 85.7+ KB


In [311]:
train_data,test_data=train_test_split(data_book,test_size=0.25)

In [312]:
for line in train_data.itertuples():
    train_data_matrix[line[2]-2,line[3]-2]=line[1]

In [313]:
train_data_matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 7.]])

In [314]:
train_data

rating  user_id_index  book_id_index
532        8            207            303
798        6            108            480
1256      10            158            818
1509       0              2           1061
479        0              4            273
...      ...            ...            ...
460        0             75            261
1641       0            408           1180
1168       0            132            747
519        0              4            296
1737       8            218           1274

[1371 rows x 3 columns]

In [315]:
from sklearn.metrics import pairwise_distances

In [316]:
user_similarity=pairwise_distances(train_data_matrix,metric='cosine')

In [317]:
books_similarity=pairwise_distances(train_data_matrix.T,metric='cosine')

In [318]:
user_similarity

array([[0., 1., 1., ..., 1., 1., 1.],
       [1., 0., 1., ..., 1., 1., 1.],
       [1., 1., 0., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 0., 1., 1.],
       [1., 1., 1., ..., 1., 0., 1.],
       [1., 1., 1., ..., 1., 1., 0.]])

In [319]:
books_similarity

array([[0., 1., 1., ..., 1., 1., 1.],
       [1., 0., 1., ..., 1., 1., 1.],
       [1., 1., 0., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 0., 1., 1.],
       [1., 1., 1., ..., 1., 0., 1.],
       [1., 1., 1., ..., 1., 1., 0.]])

In [320]:
def predict(ratings, similarity, type='user'):
    if type == 'user':
        mean_user_rating = ratings.mean(axis=1)
        #You use np.newaxis so that mean_user_rating has same format as ratings
        ratings_diff = (ratings - mean_user_rating[:, np.newaxis]) 
        pred = mean_user_rating[:, np.newaxis] + similarity.dot(ratings_diff) / np.array([np.abs(similarity).sum(axis=1)]).T
    elif type == 'item':
        pred = ratings.dot(similarity) / np.array([np.abs(similarity).sum(axis=1)])     
    return pred

In [321]:
books_prediction = predict(train_data_matrix, books_similarity, type='item')
user_prediction = predict(train_data_matrix, user_similarity, type='user')

In [322]:
user_prediction

array([[ 0.01476897,  0.03202627,  0.01476897, ...,  0.01476897,
         0.01476897,  0.02986911],
       [-0.00651285,  0.01072853, -0.00651285, ..., -0.00651285,
        -0.00651285,  0.00857336],
       [ 0.14976785,  0.16575402,  0.14976785, ...,  0.14976785,
         0.14976785,  0.16487463],
       ...,
       [-0.00651285,  0.01072853, -0.00651285, ..., -0.00651285,
        -0.00651285,  0.00857336],
       [-0.00651285,  0.01072853, -0.00651285, ..., -0.00651285,
        -0.00651285,  0.00857336],
       [-0.00137735,  0.01586403, -0.00137735, ..., -0.00137735,
        -0.00137735, -0.00137735]])

In [323]:
books_prediction

array([[0.02124542, 0.02135077, 0.02124542, ..., 0.02124542, 0.02124542,
        0.02124542],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.15604396, 0.15241558, 0.15604396, ..., 0.15604396, 0.15604396,
        0.15604396],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.00512821, 0.00515363, 0.00512821, ..., 0.00512821, 0.00512821,
        0.        ]])